#!/usr/bin/env python2
import praw
import sys
import shutil
import os

num = int(sys.argv[1])
r = praw.Reddit(user_agent='example')
s = r.get_subreddit(sys.argv[2]).get_new(limit=None)
gotten = 0
while True:
    post = next(s)
    if 'i.imgur.com' in post.url:
        os.system('curl %s -o in/%d.jpg' % (post.url, gotten))
        gotten += 1

    if gotten == num:
        exit()
