#!/usr/bin/env bash

rm -rdf in/*
./collect $1

rm -rdf out/*
cp in/0.jpg out/0.jpg
count=`expr $1 - 1`
sequence=`seq 0 $count`
for num in $sequence; do
  ./compare $2 out/$num.jpg in/$num.jpg `expr $num + 1`
done
