#!/usr/bin/env bash

rm -rdf in/*
./collect $1

rm -rdf out/*
cp in/0.jpg out/0.jpg
count=`expr $1 - 1`
sequence=`seq 0 $count`
for num in $sequence; do
  if [[ `python2 -c "print $num % 2"` == 0 ]]; then
    direction="down"
  else
    direction="right"
  fi

  ./compare `python2 -c "print $2 - .1"` out/$num.jpg in/$num.jpg `expr $num + 1` $direction
done

./compare .75 out/$1.jpg out/$1.jpg final mixup
